image: "nikolaik/python-nodejs"

stages:
  - dev

dev:
  stage: dev
  only:
    - master
  before_script:
    - npm install serverless -g
    # - sls plugin install -n serverless-python-requirements
    # - npm install serverless-pseudo-parameters
    # - npm install --save-dev serverless-step-functions
  script:
    - serverless deploy --stage dev --region ap-southeast-1 --verbose
#environment: dev